name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
   inputs:
      runGradleClean:
        description: "runGradleClean"
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!
        
  Clean:
    needs:
     - build
    runs-on: ubuntu-latest
    steps:
       - name: Set up JDK 8
         uses: actions/setup-java@v3
         with:
          java-version: '8'
          distribution: 'temurin'
          id: setup-java-8

      
       - name: Conditional Gradle Clean
         run: |
           if [ $runGradleClean -eq 'true' ] {
              echo "Running gradle clean..."
            } else {
              echo "Skipping gradle clean."
            }
          
          
